In [1]:
import numpy as numpy
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler
from warnings import filterwarnings
filterwarnings('ignore')    

In [2]:
data = pd.read_csv(r"D:\ML\project_2\india_housing_prices.csv")

In [3]:
data.head()

,ID,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,...,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status
0,1,Tamil Nadu,Chennai,Locality_84,Apartment,1,4740,489.76,0.10,1990,...,35,10,3,High,No,No,"Playground, Gym, Garden, Pool, Clubhouse",West,Owner,Ready_to_Move
1,2,Maharashtra,Pune,Locality_490,Independent House,3,2364,195.52,0.08,2008,...,17,8,1,Low,No,Yes,"Playground, Clubhouse, Pool, Gym, Garden",North,Builder,Under_Construction
2,3,Punjab,Ludhiana,Locality_167,Apartment,2,3642,183.79,0.05,1997,...,28,9,8,Low,Yes,No,"Clubhouse, Pool, Playground, Gym",South,Broker,Ready_to_Move
3,4,Rajasthan,Jodhpur,Locality_393,Independent House,2,2741,300.29,0.11,1991,...,34,5,7,High,Yes,Yes,"Playground, Clubhouse, Gym, Pool, Garden",North,Builder,Ready_to_Move
4,5,Rajasthan,Jaipur,Locality_466,Villa,4,4823,182.90,0.04,2002,...,23,4,9,Low,No,Yes,"Playground, Garden, Gym, Pool, Clubhouse",East,Builder,Ready_to_Move


In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 23 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   ID                              250000 non-null  int64  
 1   State                           250000 non-null  object 
 2   City                            250000 non-null  object 
 3   Locality                        250000 non-null  object 
 4   Property_Type                   250000 non-null  object 
 5   BHK                             250000 non-null  int64  
 6   Size_in_SqFt                    250000 non-null  int64  
 7   Price_in_Lakhs                  250000 non-null  float64
 8   Price_per_SqFt                  250000 non-null  float64
 9   Year_Built                      250000 non-null  int64  
 10  Furnished_Status                250000 non-null  object 
 11  Floor_No                        250000 non-null  int64  
 12  Total_Floors    

In [5]:
data.isnull().sum()

ID                                0
State                             0
City                              0
Locality                          0
Property_Type                     0
BHK                               0
Size_in_SqFt                      0
Price_in_Lakhs                    0
Price_per_SqFt                    0
Year_Built                        0
Furnished_Status                  0
Floor_No                          0
Total_Floors                      0
Age_of_Property                   0
Nearby_Schools                    0
Nearby_Hospitals                  0
Public_Transport_Accessibility    0
Parking_Space                     0
Security                          0
Amenities                         0
Facing                            0
Owner_Type                        0
Availability_Status               0
dtype: int64

In [6]:
from sklearn.preprocessing import LabelEncoder

encoders = {}

categorical_columns = data.select_dtypes(include='object').columns

for col in categorical_columns:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])
    encoders[col] = le

In [7]:
le = LabelEncoder()
data['City_encoded'] = le.fit_transform(data['City'])

In [8]:
mapping = dict(zip(le.classes_, range(len(le.classes_))))
print(mapping)

{np.int64(0): 0, np.int64(1): 1, np.int64(2): 2, np.int64(3): 3, np.int64(4): 4, np.int64(5): 5, np.int64(6): 6, np.int64(7): 7, np.int64(8): 8, np.int64(9): 9, np.int64(10): 10, np.int64(11): 11, np.int64(12): 12, np.int64(13): 13, np.int64(14): 14, np.int64(15): 15, np.int64(16): 16, np.int64(17): 17, np.int64(18): 18, np.int64(19): 19, np.int64(20): 20, np.int64(21): 21, np.int64(22): 22, np.int64(23): 23, np.int64(24): 24, np.int64(25): 25, np.int64(26): 26, np.int64(27): 27, np.int64(28): 28, np.int64(29): 29, np.int64(30): 30, np.int64(31): 31, np.int64(32): 32, np.int64(33): 33, np.int64(34): 34, np.int64(35): 35, np.int64(36): 36, np.int64(37): 37, np.int64(38): 38, np.int64(39): 39, np.int64(40): 40, np.int64(41): 41}


In [9]:
city_map = {
 'Mumbai':0,
 'Pune':1,
 'New Delhi':2,
 'Bangalore':3,
 'Nagpur':4,
 'Ahmedabad':5,
 'Hyderabad':6,
 'Kolkata':7,
 'Gurgaon':8
}

data['City_encoded'] = data['City'].map(city_map)

In [10]:
data.columns = data.columns.str.strip()

In [11]:
data.head()
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 24 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   ID                              250000 non-null  int64  
 1   State                           250000 non-null  int64  
 2   City                            250000 non-null  int64  
 3   Locality                        250000 non-null  int64  
 4   Property_Type                   250000 non-null  int64  
 5   BHK                             250000 non-null  int64  
 6   Size_in_SqFt                    250000 non-null  int64  
 7   Price_in_Lakhs                  250000 non-null  float64
 8   Price_per_SqFt                  250000 non-null  float64
 9   Year_Built                      250000 non-null  int64  
 10  Furnished_Status                250000 non-null  int64  
 11  Floor_No                        250000 non-null  int64  
 12  Total_Floors    

In [12]:
data["City"].unique()

array([ 6, 33, 25, 21, 19, 10,  7,  5, 30, 35, 41,  2, 29, 24, 36,  9, 31,
       13, 20,  0, 17, 12,  1, 23, 11, 40,  3, 18, 16, 28, 32, 34, 39, 38,
       22, 37, 14, 26,  8,  4, 15, 27])

In [13]:
X = data[['Size_in_SqFt','Price_per_SqFt','BHK','City','Age_of_Property']]
          
y = data['Price_in_Lakhs']

In [14]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [15]:
model = LinearRegression()
model.fit(X_train,y_train)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [16]:
pred = model.predict(X_test)

In [17]:
print("RMSE:",mean_squared_error(y_test,pred))
print("R2 Score:",r2_score(y_test,pred))

RMSE: 10164.514659113425
R2 Score: 0.4901300777208655


In [18]:
import numpy as np

print("------ House Price Prediction ------")

# User Inputs
size = float(input("Enter Size in Sqft: "))
price_sqft = float(input("Enter Price per Sqft: "))
bhk = int(input("Enter BHK: "))
city = int(input("Enter City (Encoded Value): "))
age = int(input("Enter Age of Property: "))

# Arrange input in model format
user_data = np.array([[size, price_sqft, bhk, city, age]])

# Predict price
prediction = model.predict(user_data)

price_lakh = prediction[0]



if price_lakh >= 100:
    crore = price_lakh / 100
    print("Predicted House Price:", round(crore,2), "Crore")
else:
    print("Predicted House Price:", round(price_lakh,2), "Lakhs")

------ House Price Prediction ------
Predicted House Price: 5.62 Crore


# Clasification

In [19]:
X_1 = data[['BHK','Size_in_SqFt','City','Furnished_Status','Parking_Space','Amenities','Age_of_Property']]

y_1 = data['Property_Type']

In [20]:
X_1train,X_1test,y_1train,y_1test = train_test_split(X_1,y_1,test_size=0.2,random_state=42)

In [21]:
clf = RandomForestClassifier()
clf.fit(X_1train,y_1train)

,n_estimators,100
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [22]:
from sklearn.metrics import accuracy_score
pred = clf.predict(X_1test)

print("Accuracy:",accuracy_score(y_1test,pred))

Accuracy: 0.33342


In [23]:
le = LabelEncoder()
data['Type_encoded'] = le.fit_transform(data['Property_Type'])

In [24]:
print(le.classes_)

[0 1 2]


In [25]:
type_map = {
    "Apartment":0,
    "Villa":1,
    "Independent House":2
}

In [26]:
import pickle

pickle.dump(model, open("price_model.pkl","wb"))
pickle.dump(clf, open("property_model.pkl","wb"))

In [27]:
bhk = int(input("Enter BHK: "))
size = float(input("Enter Size in Sqft: "))
city = int(input("Enter City (Encoded Value): "))
furnished = int(input("Enter Furnished Status (Encoded): "))
parking = int(input("Enter Parking Space (Encoded): "))
amenities = int(input("Enter Amenities (Encoded): "))
age = int(input("Enter Age of Property: "))

user_data = np.array([[bhk, size, city, furnished, parking, amenities, age]])

prediction = clf.predict(user_data)

print("\n------ Prediction Result ------")
print("Predicted Property Type:", prediction[0])


------ Prediction Result ------
Predicted Property Type: 1


In [28]:
data["Property_Type"].unique()



array([0, 1, 2])